import { storage } from "./storage";
import type { InsertDrawer, InsertMedication } from "@shared/schema";

const DRAWERS: InsertDrawer[] = [
  { label: "Cardiovascular", position: 1, color: "#EF4444", size: "standard" },
  { label: "Analgesics & NSAIDs", position: 2, color: "#F59E0B", size: "standard" },
  { label: "Antibiotics", position: 3, color: "#10B981", size: "standard" },
  { label: "GI & Antiemetics", position: 4, color: "#3B82F6", size: "standard" },
  { label: "Respiratory", position: 5, color: "#8B5CF6", size: "standard" },
  { label: "Controlled Substances", position: 6, color: "#EC4899", size: "standard" },
  { label: "IV Supplies & Tools", position: 7, color: "#6B7280", size: "large" },
];

export async function seedDatabase() {
  const count = await storage.getDrawerCount();
  if (count > 0) return;

  console.log("Seeding medication cart database...");

  const createdDrawers: Record<string, string> = {};
  for (const drawer of DRAWERS) {
    const created = await storage.createDrawer(drawer);
    createdDrawers[drawer.label] = created.id;
  }

  const MEDICATIONS: InsertMedication[] = [
    {
      drawerId: createdDrawers["Cardiovascular"],
      name: "Metoprolol Tartrate",
      genericName: "Metoprolol",
      brandName: "Lopressor",
      dosage: "25 mg",
      form: "Tablet",
      route: "Oral",
      frequency: "Twice daily",
      classification: "Beta-blocker",
      indication: "Used to treat hypertension, angina pectoris, and to reduce mortality following myocardial infarction.",
      contraindications: "Sinus bradycardia, heart block greater than first degree, cardiogenic shock, decompensated heart failure, sick sinus syndrome.",
      sideEffects: "Fatigue, dizziness, bradycardia, hypotension, depression, diarrhea, cold extremities.",
      nursingConsiderations: "Monitor heart rate and blood pressure before administration. Hold if HR < 60 bpm or SBP < 100 mmHg. Teach patient not to abruptly discontinue. Monitor for signs of heart failure.",
      warnings: "Do not discontinue abruptly - may cause rebound hypertension or angina. May mask signs of hypoglycemia in diabetic patients.",
      storage: "Store at room temperature 20-25°C (68-77°F). Protect from moisture.",
      manufacturer: "Novartis",
      ndcNumber: "0078-0371-05",
      controlledSubstance: false,
      color: "#EF4444",
      itemType: "medication",
      prepMethod: "cup",
      prepTargetAmount: "1",
      prepTargetUnit: "tablet",
      prepMaxAmount: "4",
    },
    {
      drawerId: createdDrawers["Cardiovascular"],
      name: "Lisinopril",
      genericName: "Lisinopril",
      brandName: "Zestril",
      dosage: "10 mg",
      form: "Tablet",
      route: "Oral",
      frequency: "Once daily",
      classification: "ACE Inhibitor",
      indication: "Treatment of hypertension, heart failure, and to improve survival after myocardial infarction.",
      contraindications: "History of angioedema related to previous ACE inhibitor therapy, hereditary or idiopathic angioedema, pregnancy.",
      sideEffects: "Persistent dry cough, dizziness, headache, hyperkalemia, hypotension, elevated creatinine.",
      nursingConsiderations: "Monitor blood pressure, potassium levels, and renal function. Assess for dry cough. Ensure adequate hydration. Not safe during pregnancy - advise patients of childbearing age.",
      warnings: "Risk of angioedema - can occur at any time during treatment. May cause fetal toxicity. Monitor renal function closely.",
      storage: "Store at room temperature 20-25°C (68-77°F). Protect from moisture and light.",
      manufacturer: "AstraZeneca",
      ndcNumber: "0310-0152-30",
      controlledSubstance: false,
      color: "#EF4444",
      itemType: "medication",
      prepMethod: "cup",
      prepTargetAmount: "1",
      prepTargetUnit: "tablet",
      prepMaxAmount: "4",
    },
    {
      drawerId: createdDrawers["Cardiovascular"],
      name: "Furosemide",
      genericName: "Furosemide",
      brandName: "Lasix",
      dosage: "40 mg",
      form: "Tablet",
      route: "Oral / IV",
      frequency: "Once or twice daily",
      classification: "Loop Diuretic",
      indication: "Treatment of edema associated with heart failure, hepatic cirrhosis, and renal disease. Also used for hypertension.",
      contraindications: "Anuria, hepatic coma, severe electrolyte depletion, hypersensitivity to sulfonamides.",
      sideEffects: "Hypokalemia, hyponatremia, dehydration, hypotension, ototoxicity (high doses), hyperglycemia.",
      nursingConsiderations: "Monitor I&O, daily weights, electrolytes (especially potassium), blood glucose, and renal function. Administer in morning to prevent nocturia. Monitor for signs of dehydration.",
      warnings: "Excessive diuresis may lead to dehydration and electrolyte depletion. Ototoxicity risk increases with rapid IV injection.",
      storage: "Store at room temperature 15-30°C (59-86°F). Protect from light. Discard discolored solutions.",
      manufacturer: "Sanofi",
      ndcNumber: "0039-0060-13",
      controlledSubstance: false,
      color: "#EF4444",
      itemType: "medication",
      prepMethod: "cup",
      prepTargetAmount: "1",
      prepTargetUnit: "tablet",
      prepMaxAmount: "4",
    },

    {
      drawerId: createdDrawers["Analgesics & NSAIDs"],
      name: "Acetaminophen",
      genericName: "Acetaminophen",
      brandName: "Tylenol",
      dosage: "500 mg",
      form: "Tablet",
      route: "Oral",
      frequency: "Every 4-6 hours PRN",
      classification: "Analgesic / Antipyretic",
      indication: "Relief of mild to moderate pain and reduction of fever.",
      contraindications: "Severe hepatic impairment, active liver disease.",
      sideEffects: "Rare at therapeutic doses. Hepatotoxicity with overdose, allergic reactions (rare).",
      nursingConsiderations: "Do not exceed 4g/day total from all sources. Monitor liver function in chronic use. Assess pain level before and after administration. Check all medications for hidden acetaminophen.",
      warnings: "HEPATOTOXICITY: Do not exceed maximum daily dose. Alcohol use increases risk of liver damage. Many OTC products contain acetaminophen - check total daily intake.",
      storage: "Store at room temperature 20-25°C (68-77°F).",
      manufacturer: "Johnson & Johnson",
      ndcNumber: "0045-0481-10",
      controlledSubstance: false,
      color: "#F59E0B",
      itemType: "medication",
      prepMethod: "cup",
      prepTargetAmount: "2",
      prepTargetUnit: "tablet",
      prepMaxAmount: "6",
    },
    {
      drawerId: createdDrawers["Analgesics & NSAIDs"],
      name: "Ibuprofen",
      genericName: "Ibuprofen",
      brandName: "Advil / Motrin",
      dosage: "400 mg",
      form: "Tablet",
      route: "Oral",
      frequency: "Every 6-8 hours PRN",
      classification: "NSAID",
      indication: "Relief of mild to moderate pain, inflammation, fever, dysmenorrhea, and arthritis.",
      contraindications: "Active GI bleeding, severe renal impairment, perioperative pain in CABG surgery, third trimester of pregnancy.",
      sideEffects: "GI upset, nausea, dyspepsia, GI bleeding, headache, dizziness, fluid retention, elevated blood pressure.",
      nursingConsiderations: "Administer with food or milk to reduce GI irritation. Monitor renal function, CBC, and signs of GI bleeding. Assess pain before and after administration. Monitor blood pressure in hypertensive patients.",
      warnings: "NSAIDs increase cardiovascular thrombotic events risk, including MI and stroke. GI bleeding, ulceration, and perforation can occur at any time.",
      storage: "Store at room temperature 20-25°C (68-77°F).",
      manufacturer: "Pfizer",
      ndcNumber: "0573-0155-20",
      controlledSubstance: false,
      color: "#F59E0B",
      itemType: "medication",
      prepMethod: "cup",
      prepTargetAmount: "1",
      prepTargetUnit: "tablet",
      prepMaxAmount: "4",
    },
    {
      drawerId: createdDrawers["Analgesics & NSAIDs"],
      name: "Ketorolac Tromethamine",
      genericName: "Ketorolac",
      brandName: "Toradol",
      dosage: "30 mg/mL",
      form: "Injection (Vial)",
      route: "IM / IV",
      frequency: "Every 6 hours PRN (max 5 days)",
      classification: "NSAID",
      indication: "Short-term management of moderately severe acute pain that requires analgesia at the opioid level.",
      contraindications: "Active or history of peptic ulcer disease, renal impairment, pregnancy (labor and delivery), nursing mothers, patients at risk for bleeding.",
      sideEffects: "GI pain, nausea, injection site pain, headache, drowsiness, edema.",
      nursingConsiderations: "Limit use to 5 days maximum. Monitor renal function, signs of GI bleeding, and bleeding time. Not for minor or chronic painful conditions. Assess pain before and after.",
      warnings: "BOXED WARNING: Increased risk of serious cardiovascular thrombotic events, GI bleeding, ulceration, and perforation. Not to be used for more than 5 days. Contraindicated for perioperative pain in CABG surgery.",
      storage: "Store at room temperature 15-30°C (59-86°F). Protect from light.",
      manufacturer: "Roche",
      ndcNumber: "0004-1918-01",
      controlledSubstance: false,
      color: "#F59E0B",
      itemType: "medication",
      prepMethod: "syringe",
      prepTargetAmount: "1.0",
      prepTargetUnit: "mL",
      prepMaxAmount: "5",
    },

    {
      drawerId: createdDrawers["Antibiotics"],
      name: "Ceftriaxone",
      genericName: "Ceftriaxone Sodium",
      brandName: "Rocephin",
      dosage: "1 g",
      form: "Powder for Injection",
      route: "IM / IV",
      frequency: "Once or twice daily",
      classification: "Cephalosporin (3rd Generation)",
      indication: "Treatment of serious infections including lower respiratory tract, UTI, bacterial septicemia, bone/joint infections, meningitis, and surgical prophylaxis.",
      contraindications: "Known hypersensitivity to cephalosporins. Neonates with hyperbilirubinemia. Do not mix with calcium-containing IV solutions in neonates.",
      sideEffects: "Diarrhea, rash, injection site reactions, eosinophilia, elevated liver enzymes, C. difficile-associated diarrhea.",
      nursingConsiderations: "Assess for penicillin/cephalosporin allergy before administration. Monitor for signs of superinfection. Obtain C&S before first dose. Monitor IV site for phlebitis. Reconstitute per package instructions.",
      warnings: "Cross-sensitivity with penicillin allergies possible. C. difficile-associated diarrhea reported with all antibacterials. Do not co-administer with calcium in neonates.",
      storage: "Store powder at 25°C (77°F). After reconstitution, stable for 24 hours at room temperature or 10 days refrigerated.",
      manufacturer: "Roche",
      ndcNumber: "0004-1963-01",
      controlledSubstance: false,
      color: "#10B981",
      itemType: "medication",
      prepMethod: "syringe",
      prepTargetAmount: "3.5",
      prepTargetUnit: "mL",
      prepMaxAmount: "10",
    },
    {
      drawerId: createdDrawers["Antibiotics"],
      name: "Amoxicillin",
      genericName: "Amoxicillin",
      brandName: "Amoxil",
      dosage: "500 mg",
      form: "Capsule",
      route: "Oral",
      frequency: "Every 8 hours",
      classification: "Penicillin Antibiotic",
      indication: "Treatment of infections of the ear, nose, throat, urinary tract, skin, and lower respiratory tract caused by susceptible organisms.",
      contraindications: "Known hypersensitivity to penicillins. Use with caution in patients with cephalosporin allergy.",
      sideEffects: "Diarrhea, nausea, skin rash, vomiting, allergic reactions.",
      nursingConsiderations: "Assess for penicillin allergy before first dose. Obtain C&S before starting therapy. Monitor for signs of superinfection. Instruct patient to complete full course. May reduce effectiveness of oral contraceptives.",
      warnings: "Serious and occasionally fatal hypersensitivity (anaphylaxis) reported. C. difficile-associated diarrhea possible. Maculopapular rash common with EBV infection.",
      storage: "Store capsules at 20°C (68°F). Keep tightly closed.",
      manufacturer: "GlaxoSmithKline",
      ndcNumber: "0029-6008-13",
      controlledSubstance: false,
      color: "#10B981",
      itemType: "medication",
      prepMethod: "cup",
      prepTargetAmount: "1",
      prepTargetUnit: "capsule",
      prepMaxAmount: "4",
    },
    {
      drawerId: createdDrawers["Antibiotics"],
      name: "Vancomycin",
      genericName: "Vancomycin HCl",
      brandName: "Vancocin",
      dosage: "1 g",
      form: "Powder for IV Infusion",
      route: "IV",
      frequency: "Every 12 hours",
      classification: "Glycopeptide Antibiotic",
      indication: "Treatment of serious infections caused by susceptible strains of methicillin-resistant staphylococci (MRSA). Also used for C. difficile colitis (oral form).",
      contraindications: "Known hypersensitivity to vancomycin.",
      sideEffects: "Red man syndrome (rapid infusion), nephrotoxicity, ototoxicity, thrombophlebitis, chills.",
      nursingConsiderations: "Infuse over at least 60 minutes to prevent Red Man Syndrome. Monitor vancomycin trough levels (target 15-20 mcg/mL for serious infections). Monitor renal function (BUN, creatinine). Assess hearing periodically. Monitor IV site.",
      warnings: "Ototoxicity may be enhanced with concurrent aminoglycosides. Nephrotoxicity risk increases with high doses and prolonged use. Red Man Syndrome with rapid infusion - not a true allergy.",
      storage: "Store powder at room temperature. After reconstitution, refrigerate and use within 14 days.",
      manufacturer: "Pfizer",
      ndcNumber: "0049-0500-83",
      controlledSubstance: false,
      color: "#10B981",
      itemType: "medication",
      prepMethod: "syringe",
      prepTargetAmount: "5.0",
      prepTargetUnit: "mL",
      prepMaxAmount: "10",
    },

    {
      drawerId: createdDrawers["GI & Antiemetics"],
      name: "Ondansetron",
      genericName: "Ondansetron HCl",
      brandName: "Zofran",
      dosage: "4 mg",
      form: "Tablet (ODT)",
      route: "Oral / IV",
      frequency: "Every 4-8 hours PRN",
      classification: "5-HT3 Receptor Antagonist / Antiemetic",
      indication: "Prevention and treatment of nausea and vomiting associated with chemotherapy, radiation, and surgery.",
      contraindications: "Known hypersensitivity. Concomitant use of apomorphine.",
      sideEffects: "Headache, constipation, dizziness, fatigue, QT prolongation (rare).",
      nursingConsiderations: "Monitor for QT prolongation, especially with IV administration. ODT form dissolves on tongue without water. Assess effectiveness of antiemetic action. Monitor electrolytes with prolonged use.",
      warnings: "ECG monitoring recommended in patients with electrolyte abnormalities or congestive heart failure. Serotonin syndrome possible with concurrent serotonergic drugs.",
      storage: "Store at room temperature 20-25°C (68-77°F). Protect from light. ODT: Keep in blister pack until ready to use.",
      manufacturer: "GlaxoSmithKline",
      ndcNumber: "0173-0477-00",
      controlledSubstance: false,
      color: "#3B82F6",
      itemType: "medication",
      prepMethod: "cup",
      prepTargetAmount: "1",
      prepTargetUnit: "tablet",
      prepMaxAmount: "4",
    },
    {
      drawerId: createdDrawers["GI & Antiemetics"],
      name: "Pantoprazole",
      genericName: "Pantoprazole Sodium",
      brandName: "Protonix",
      dosage: "40 mg",
      form: "Tablet (Delayed-Release)",
      route: "Oral",
      frequency: "Once daily, before breakfast",
      classification: "Proton Pump Inhibitor",
      indication: "Short-term treatment of erosive esophagitis associated with GERD. Maintenance of healing of erosive esophagitis. Zollinger-Ellison syndrome.",
      contraindications: "Known hypersensitivity to any PPI or substituted benzimidazoles.",
      sideEffects: "Headache, diarrhea, nausea, abdominal pain, flatulence, vitamin B12 deficiency (long-term).",
      nursingConsiderations: "Administer before meals. Do not crush or chew delayed-release tablets. Monitor for C. difficile in patients with diarrhea. Long-term use: monitor magnesium, vitamin B12, and bone density.",
      warnings: "Long-term use associated with increased risk of bone fractures, C. difficile infection, hypomagnesemia, and vitamin B12 deficiency. May reduce absorption of drugs dependent on gastric pH.",
      storage: "Store at room temperature 20-25°C (68-77°F).",
      manufacturer: "Pfizer",
      ndcNumber: "0008-0841-81",
      controlledSubstance: false,
      color: "#3B82F6",
      itemType: "medication",
      prepMethod: "cup",
      prepTargetAmount: "1",
      prepTargetUnit: "tablet",
      prepMaxAmount: "4",
    },

    {
      drawerId: createdDrawers["Respiratory"],
      name: "Albuterol Sulfate",
      genericName: "Albuterol",
      brandName: "ProAir HFA / Ventolin",
      dosage: "90 mcg/actuation",
      form: "Metered-Dose Inhaler (MDI)",
      route: "Inhalation",
      frequency: "Every 4-6 hours PRN",
      classification: "Short-Acting Beta-2 Agonist (SABA)",
      indication: "Treatment and prevention of bronchospasm in patients with reversible obstructive airway disease. Prevention of exercise-induced bronchospasm.",
      contraindications: "Known hypersensitivity to albuterol or any component.",
      sideEffects: "Tachycardia, tremor, nervousness, headache, throat irritation, paradoxical bronchospasm.",
      nursingConsiderations: "Teach proper MDI technique (shake, exhale, inhale slowly, hold breath 10 seconds). Wait 1-2 minutes between puffs. Rinse mouth after use if using with corticosteroids. Monitor heart rate and respiratory status.",
      warnings: "Excessive use may indicate deteriorating asthma control. Paradoxical bronchospasm possible - discontinue if occurs. May cause hypokalemia.",
      storage: "Store at room temperature 15-25°C (59-77°F). Do not puncture or expose to heat. Shake well before use.",
      manufacturer: "Teva",
      ndcNumber: "0093-7610-57",
      controlledSubstance: false,
      color: "#8B5CF6",
      itemType: "medication",
      prepMethod: null,
      prepTargetAmount: null,
      prepTargetUnit: null,
      prepMaxAmount: null,
    },
    {
      drawerId: createdDrawers["Respiratory"],
      name: "Ipratropium Bromide",
      genericName: "Ipratropium Bromide",
      brandName: "Atrovent HFA",
      dosage: "0.5 mg/2.5 mL",
      form: "Nebulizer Solution",
      route: "Inhalation (Nebulizer)",
      frequency: "Every 6-8 hours",
      classification: "Anticholinergic Bronchodilator",
      indication: "Maintenance treatment of bronchospasm associated with COPD, including chronic bronchitis and emphysema.",
      contraindications: "Known hypersensitivity to ipratropium or atropine derivatives.",
      sideEffects: "Dry mouth, cough, headache, nausea, dizziness, blurred vision (if medication gets in eyes).",
      nursingConsiderations: "Protect eyes from spray - may cause pupil dilation and blurred vision. Not for acute bronchospasm rescue. Monitor respiratory status. Can be mixed with albuterol in nebulizer.",
      warnings: "Not intended as primary treatment for acute episodes of bronchospasm. Paradoxical bronchospasm may occur. Use with caution in narrow-angle glaucoma and prostatic hyperplasia.",
      storage: "Store at room temperature 25°C (77°F). Protect from light.",
      manufacturer: "Boehringer Ingelheim",
      ndcNumber: "0597-0082-17",
      controlledSubstance: false,
      color: "#8B5CF6",
      itemType: "medication",
      prepMethod: "syringe",
      prepTargetAmount: "2.5",
      prepTargetUnit: "mL",
      prepMaxAmount: "5",
    },

    {
      drawerId: createdDrawers["Controlled Substances"],
      name: "Morphine Sulfate",
      genericName: "Morphine Sulfate",
      brandName: "MS Contin / Morphine",
      dosage: "4 mg/mL",
      form: "Injection (Vial)",
      route: "IV / IM / SC",
      frequency: "Every 3-4 hours PRN",
      classification: "Opioid Analgesic",
      indication: "Management of moderate to severe acute and chronic pain where use of an opioid analgesic is appropriate.",
      contraindications: "Significant respiratory depression, acute or severe bronchial asthma, known or suspected GI obstruction, concurrent use of MAOIs.",
      sideEffects: "Respiratory depression, sedation, constipation, nausea, vomiting, pruritus, urinary retention, hypotension.",
      nursingConsiderations: "ASSESS respiratory rate before administration - hold if RR < 12. Monitor pain level using standardized scale. Monitor oxygen saturation. Keep naloxone readily available. Assess bowel function and implement bowel regimen. Monitor sedation level.",
      warnings: "BOXED WARNING: Risk of addiction, abuse, and misuse. Life-threatening respiratory depression. Neonatal opioid withdrawal syndrome. Concomitant use with benzodiazepines or CNS depressants may result in death.",
      storage: "Store at 20-25°C (68-77°F). Protect from light. Keep in locked cabinet per facility protocol.",
      manufacturer: "West-Ward",
      ndcNumber: "0641-6151-25",
      controlledSubstance: true,
      scheduleClass: "Schedule II",
      color: "#EC4899",
      itemType: "medication",
      prepMethod: "syringe",
      prepTargetAmount: "1.0",
      prepTargetUnit: "mL",
      prepMaxAmount: "5",
    },
    {
      drawerId: createdDrawers["Controlled Substances"],
      name: "Hydromorphone",
      genericName: "Hydromorphone HCl",
      brandName: "Dilaudid",
      dosage: "2 mg/mL",
      form: "Injection (Vial)",
      route: "IV / IM / SC",
      frequency: "Every 3-6 hours PRN",
      classification: "Opioid Analgesic",
      indication: "Management of pain severe enough to require an opioid analgesic and for which alternative treatments are inadequate.",
      contraindications: "Significant respiratory depression, acute or severe bronchial asthma, known or suspected GI obstruction, hypersensitivity to hydromorphone.",
      sideEffects: "Respiratory depression, sedation, constipation, nausea, vomiting, pruritus, dizziness, lightheadedness.",
      nursingConsiderations: "HIGH ALERT medication - approximately 5x more potent than morphine. Verify dose carefully. Assess respiratory rate before administration (hold if RR < 12). Have naloxone available. Implement fall precautions. Assess pain before and after.",
      warnings: "BOXED WARNING: Addiction, abuse, misuse potential. Life-threatening respiratory depression. Not for opioid-naïve patients. Accidental ingestion may cause fatal overdose. Concomitant use with benzodiazepines may be fatal.",
      storage: "Store at 25°C (77°F). Protect from light. Store in locked narcotic cabinet. Requires witness for waste.",
      manufacturer: "Purdue Pharma",
      ndcNumber: "0591-3733-01",
      controlledSubstance: true,
      scheduleClass: "Schedule II",
      color: "#EC4899",
      itemType: "medication",
      prepMethod: "syringe",
      prepTargetAmount: "1.0",
      prepTargetUnit: "mL",
      prepMaxAmount: "5",
    },
    {
      drawerId: createdDrawers["Controlled Substances"],
      name: "Lorazepam",
      genericName: "Lorazepam",
      brandName: "Ativan",
      dosage: "2 mg/mL",
      form: "Injection (Vial)",
      route: "IV / IM",
      frequency: "Every 6-8 hours PRN",
      classification: "Benzodiazepine",
      indication: "Management of anxiety disorders, insomnia, preoperative sedation, status epilepticus, and alcohol withdrawal.",
      contraindications: "Known hypersensitivity to benzodiazepines, acute narrow-angle glaucoma, sleep apnea.",
      sideEffects: "Sedation, dizziness, weakness, unsteadiness, amnesia, respiratory depression, paradoxical agitation.",
      nursingConsiderations: "Monitor respiratory status and sedation level. Have flumazenil (reversal agent) available. Implement fall precautions. IV: dilute with equal volume of compatible diluent, inject slowly at max 2 mg/min. Monitor vital signs q5min during IV administration.",
      warnings: "BOXED WARNING: Concomitant use with opioids may result in respiratory depression, coma, death. Risk of dependence and withdrawal. Not for long-term use when possible.",
      storage: "Refrigerate at 2-8°C (36-46°F). Protect from light. May store at room temperature up to 60 days.",
      manufacturer: "Baxter",
      ndcNumber: "0641-6003-01",
      controlledSubstance: true,
      scheduleClass: "Schedule IV",
      color: "#EC4899",
      itemType: "medication",
      prepMethod: "syringe",
      prepTargetAmount: "1.0",
      prepTargetUnit: "mL",
      prepMaxAmount: "5",
    },

    {
      drawerId: createdDrawers["IV Supplies & Tools"],
      name: "Blood Pressure Cuff (Adult)",
      genericName: "Sphygmomanometer",
      brandName: null,
      dosage: "Standard adult size, upper arm",
      form: "Tool",
      route: "N/A",
      frequency: null,
      classification: "Monitoring Equipment",
      indication: "Measurement of arterial blood pressure. Essential vital sign assessment tool.",
      contraindications: null,
      sideEffects: null,
      nursingConsiderations: "Select appropriate cuff size (width should be 40% of arm circumference). Place cuff 1 inch above antecubital fossa. Support arm at heart level. Do not use on arm with IV, fistula, or on affected side post-mastectomy.",
      warnings: null,
      storage: "Clean after each use per facility protocol. Store in clean, dry location.",
      manufacturer: "Welch Allyn",
      ndcNumber: null,
      controlledSubstance: false,
      color: "#6B7280",
      itemType: "tool",
    },
    {
      drawerId: createdDrawers["IV Supplies & Tools"],
      name: "Pulse Oximeter",
      genericName: "SpO2 Sensor",
      brandName: null,
      dosage: "Finger clip sensor, adult",
      form: "Tool",
      route: "N/A",
      frequency: null,
      classification: "Monitoring Equipment",
      indication: "Continuous or spot-check monitoring of oxygen saturation (SpO2) and pulse rate.",
      contraindications: null,
      sideEffects: null,
      nursingConsiderations: "Ensure clean, dry finger. Remove nail polish or artificial nails if present. Avoid placing on same extremity as blood pressure cuff. Normal SpO2: 95-100%. Report values < 90% immediately. Verify with ABG if readings are questionable.",
      warnings: null,
      storage: "Clean sensor between patients. Store in designated location.",
      manufacturer: "Nonin Medical",
      ndcNumber: null,
      controlledSubstance: false,
      color: "#6B7280",
      itemType: "tool",
    },
    {
      drawerId: createdDrawers["IV Supplies & Tools"],
      name: "IV Start Kit",
      genericName: "Peripheral IV Catheter Kit",
      brandName: null,
      dosage: "Contains: 20G & 22G catheters, tourniquet, tegaderm, alcohol swabs, gauze, tape, saline flush",
      form: "Supply Kit",
      route: "N/A",
      frequency: null,
      classification: "IV Access Supplies",
      indication: "Used for establishing peripheral intravenous access for fluid administration, medication delivery, and blood draws.",
      contraindications: null,
      sideEffects: null,
      nursingConsiderations: "Use aseptic technique. Select appropriate gauge: 20G for most adults, 22G for elderly/pediatric. Assess insertion site regularly for signs of infiltration, phlebitis, or infection. Document site, gauge, and number of attempts. Change dressing per facility policy.",
      warnings: "Single-use sterile supplies. Do not use if packaging is damaged. Observe standard precautions.",
      storage: "Store in clean, dry area at room temperature. Check expiration dates regularly.",
      manufacturer: "BD Medical",
      ndcNumber: null,
      controlledSubstance: false,
      color: "#6B7280",
      itemType: "supply",
    },
    {
      drawerId: createdDrawers["IV Supplies & Tools"],
      name: "Stethoscope",
      genericName: "Acoustic Stethoscope",
      brandName: "Littmann Classic III",
      dosage: "Dual-head (bell and diaphragm), adult",
      form: "Tool",
      route: "N/A",
      frequency: null,
      classification: "Assessment Equipment",
      indication: "Auscultation of heart sounds, lung sounds, bowel sounds, and blood pressure measurement.",
      contraindications: null,
      sideEffects: null,
      nursingConsiderations: "Clean earpieces and diaphragm before and after each patient use. Use bell for low-frequency sounds (S3, S4, murmurs). Use diaphragm for high-frequency sounds (S1, S2, breath sounds, bowel sounds). Ensure proper ear tip fit.",
      warnings: null,
      storage: "Clean with alcohol wipe after each use. Do not immerse in liquid. Store around neck or in clean case.",
      manufacturer: "3M Littmann",
      ndcNumber: null,
      controlledSubstance: false,
      color: "#6B7280",
      itemType: "tool",
    },
  ];

  for (const med of MEDICATIONS) {
    await storage.createMedication(med);
  }

  console.log("Seed data inserted successfully.");
}
